"use strict";
const canvas=document.getElementById('canvas');const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});let W=0,H=0;
let videoSettings={quality:'auto',resolution:'auto',renderer:'auto',fps:60};let effectiveQuality='high';
let gameplaySettings={damageNumbers:true,screenShake:true,fullscreen:false};
try{Object.assign(gameplaySettings,JSON.parse(localStorage.getItem('noiteAmaldicoada_gameplay_v2')||'{}'));}catch(e){}
function loadVideoSettings(){try{Object.assign(videoSettings,JSON.parse(localStorage.getItem('noiteAmaldicoada_video_v2')||'{}'));}catch(e){}}
function chooseAutoQuality(){const cores=navigator.hardwareConcurrency||4,mem=navigator.deviceMemory||4;if(cores<=2||mem<=2)return'low';if(cores<=4||mem<=4)return'medium';return'high';}
function applyCanvasResolution(){let rw,rh;if(videoSettings.resolution==='auto'){const scale=effectiveQuality==='low'?.65:effectiveQuality==='medium'?.82:1;rw=Math.round(Math.min(innerWidth,1600)*scale);rh=Math.round(Math.min(innerHeight,900)*scale);}else{const p=videoSettings.resolution.split('x');rw=+p[0];rh=+p[1];}W=canvas.width=Math.max(480,rw);H=canvas.height=Math.max(270,rh);canvas.style.imageRendering=effectiveQuality==='low'?'pixelated':'auto';canvas.style.transform=videoSettings.renderer==='compatible'?'none':'translateZ(0)';if(typeof initFog==='function')initFog();}
loadVideoSettings();effectiveQuality=videoSettings.quality==='auto'?chooseAutoQuality():videoSettings.quality;applyCanvasResolution();addEventListener('resize',()=>{if(videoSettings.resolution==='auto')applyCanvasResolution();});
const $=id=>document.getElementById(id);
const hpFill=$('hpBarFill'),xpFill=$('xpBarFill'),levelLabel=$('levelLabel'),timerLabel=$('timerLabel'),killLabel=$('killLabel'),weaponBar=$('weaponBar'),overlay=$('overlay'),overlayTitle=$('overlayTitle'),overlaySub=$('overlaySub'),cardWrap=$('cardWrap'),startScreen=$('startScreen'),startBtn=$('startBtn'),continueBtn=$('continueBtn'),storeBtn=$('storeBtn'),storeScreen=$('storeScreen'),storeBackBtn=$('storeBackBtn'),storeGrid=$('storeGrid'),currencyValue=$('currencyValue'),storeCurrencyValue=$('storeCurrencyValue'),runCurrencyValue=$('runCurrencyValue'),pauseScreen=$('pauseScreen'),resumeBtn=$('resumeBtn'),restartBtn=$('restartBtn'),quitBtn=$('quitBtn'),saveQuitBtn=$('saveQuitBtn'),sfxVolSlider=$('sfxVolSlider'),musicVolSlider=$('musicVolSlider'),sfxVolLabel=$('sfxVolLabel'),musicVolLabel=$('musicVolLabel'),muteCheckbox=$('muteCheckbox'),settingsBtn=$('settingsBtn'),settingsScreen=$('settingsScreen'),settingsBackBtn=$('settingsBackBtn'),settingsApplyBtn=$('settingsApplyBtn'),qualitySelect=$('qualitySelect'),resolutionSelect=$('resolutionSelect'),rendererSelect=$('rendererSelect'),fpsSelect=$('fpsSelect'),gpuInfo=$('gpuInfo'),loadingScreen=$('loadingScreen'),loadingTitle=$('loadingTitle'),loadingText=$('loadingText'),loadingFill=$('loadingFill'),loadingPct=$('loadingPct'),stageBadge=$('stageBadge'),perfBadge=$('perfBadge'),stageTimerLabel=$('stageTimerLabel'),fullscreenCheckbox=$('fullscreenCheckbox'),damageNumbersCheckbox=$('damageNumbersCheckbox'),shakeCheckbox=$('shakeCheckbox'),gamepadCheckbox=$('gamepadCheckbox'),bindUp=$('bindUp'),bindDown=$('bindDown'),bindLeft=$('bindLeft'),bindRight=$('bindRight');
const keys={};const GAME_KEYS=new Set(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' ']);addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(GAME_KEYS.has(k)&&running)e.preventDefault();},{passive:false});addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys[k]=false;if(GAME_KEYS.has(k)&&running)e.preventDefault();},{passive:false});addEventListener('wheel',e=>{if(running)e.preventDefault();},{passive:false});
function dist2(ax,ay,bx,by){const dx=ax-bx,dy=ay-by;return dx*dx+dy*dy;}function rand(a,b){return Math.random()*(b-a)+a;}function choice(a){return a[Math.floor(Math.random()*a.length)];}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
