"use strict";
let pendingGameOver=false;
function updateWeaponBar(){weaponBar.innerHTML='';for(const k of Object.keys(playerWeapons)){const d=WEAPON_DEFS[k],div=document.createElement('div');div.className='weaponIcon'+(evolvedWeapons[k]?' evolved':'');div.innerHTML=`${evolvedWeapons[k]?(EVOLUTION_DEFS[k]?.icon||d.icon):d.icon}<span class="lvl">${evolvedWeapons[k]?'E':playerWeapons[k]}</span>`;weaponBar.appendChild(div);}for(const k of Object.keys(playerPassives)){const d=PASSIVE_DEFS[k],div=document.createElement('div');div.className='weaponIcon passive';div.innerHTML=`${d.icon}<span class="lvl">${playerPassives[k]}</span>`;weaponBar.appendChild(div);}}
function updateHud(){hpFill.style.width=clamp(player.hp/player.maxHp*100,0,100)+'%';xpFill.style.width=clamp(player.xp/player.xpToNext*100,0,100)+'%';levelLabel.textContent='Nível '+player.level;const m=Math.floor(gameTime/60).toString().padStart(2,'0'),s=Math.floor(gameTime%60).toString().padStart(2,'0');timerLabel.textContent=`${m}:${s}`;killLabel.textContent=`Abates: ${killCount} · 💠 ${runFragments}`;if(stageTimerLabel)stageTimerLabel.textContent=Math.max(0,Math.ceil(getStage().bossAt-stageTime))+'s até o chefe';}
function finishOverlay(title,subtitle){running=false;paused=true;stopAmbient();clearRunSave();overlayTitle.textContent=title;overlaySub.textContent=subtitle;cardWrap.innerHTML='';const stats=document.createElement('div');stats.className='runStats';stats.innerHTML=`<b>Resumo da Run</b><span>Abates: ${killCount}</span><span>Elites: ${eliteKills}</span><span>Chefes: ${bossKills}</span><span>Nível: ${player.level}</span><span>💠 Encontrados: ${runStats.fragmentsCollected}</span><span>Baús: ${runStats.chestsOpened}</span><span>Dano causado: ${Math.round(runStats.damageDealt)}</span><span>Dano recebido: ${Math.round(runStats.damageTaken)}</span>`;cardWrap.appendChild(stats);const again=document.createElement('div');again.className='card';again.innerHTML='<div class="icon">🌙</div><div class="name">Nova Run</div><div class="desc">Começar novamente desde a Noite I.</div>';again.onclick=()=>{overlay.classList.remove('active');startAmbient();resetGame();runStageLoading(0,true);};cardWrap.appendChild(again);const shop=document.createElement('div');shop.className='card';shop.innerHTML='<div class="icon">🏰</div><div class="name">Loja Sombria</div><div class="desc">Gastar as moedas permanentes.</div>';shop.onclick=()=>{overlay.classList.remove('active');startScreen.style.display='flex';renderStore();storeScreen.classList.add('active');};cardWrap.appendChild(shop);overlay.classList.add('active');}
function finalizeGameOver(){const bonus=Math.floor(killCount/10)+bossKills*2;if(bonus)addPermanentCurrency(bonus);pendingGameOver=false;finishOverlay('VOCÊ SUCUMBIU ÀS TREVAS',`Sobreviveu ${timerLabel.textContent} · bônus final 💠 ${bonus}`);}
function beginGameOverSequence(){if(pendingGameOver)return;pendingGameOver=true;paused=true;manualPause=false;pauseScreen.classList.remove('active');sfxGameOver();stopAmbient();clearRunSave();triggerPlayerDeath(()=>finalizeGameOver());}
function gameOver(){beginGameOverSequence();}
function victoryGame(){meta.wins=(meta.wins||0)+1;const bonus=20+bossKills*3;addPermanentCurrency(bonus);saveMeta();finishOverlay('A MALDIÇÃO FOI QUEBRADA',`Você venceu as seis noites · bônus de vitória 💠 ${bonus}`);}
