"use strict";
function worldToScreen(x,y){return[x-player.x+W/2,y-player.y+H/2];}
function hash2(ix,iy){const n=(ix*374761393+iy*668265263)>>>0;return ((n^(n>>>13))*1274126177)>>>0;}
function drawBackground(){const st=getStage(),img=AssetManager.get('bg:'+st.id);if(img){const b=getStageBounds();const camLeft=player.x-W/2, camTop=player.y-H/2;const worldW=Math.max(1,(b.maxX-b.minX)), worldH=Math.max(1,(b.maxY-b.minY));const u=clamp((camLeft-b.minX)/Math.max(1,worldW-W),0,1), v=clamp((camTop-b.minY)/Math.max(1,worldH-H),0,1);if(img.width>=W&&img.height>=H){const sx=Math.round(u*Math.max(0,img.width-W));const sy=Math.round(v*Math.max(0,img.height-H));ctx.drawImage(img,sx,sy,W,H,0,0,W,H);}else{const scale=Math.max(W/img.width,H/img.height),iw=img.width*scale,ih=img.height*scale,dx=-u*Math.max(0,iw-W),dy=-v*Math.max(0,ih-H);ctx.drawImage(img,dx,dy,iw,ih);}ctx.fillStyle='rgba(0,0,0,.08)';ctx.fillRect(0,0,W,H);}else{ctx.fillStyle=['#0d0812','#100914','#090811','#13080d','#09070f','#060408'][currentStage]||'#0d0812';ctx.fillRect(0,0,W,H);const g=80,ox=((player.x%g)+g)%g,oy=((player.y%g)+g)%g;ctx.strokeStyle='rgba(110,60,100,.07)';for(let x=-ox;x<W;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=-oy;y<H;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}}drawFog();}
let groundPatternCache=null,groundPatternImage=null;
function drawGroundLayer(){
 const st=getStage();if(st.id!=='stage0')return;
 const img=getGroundAsset('stage0','pattern');if(!img)return;
 if(groundPatternImage!==img){groundPatternCache=ctx.createPattern(img,'repeat');groundPatternImage=img;}
 if(!groundPatternCache)return;
 const ox=Math.round(((-player.x+W/2)%img.width+img.width)%img.width),oy=Math.round(((-player.y+H/2)%img.height+img.height)%img.height);
 // This layer is only a floor-detail overlay. It must never cover the real stage background.
 ctx.save();
 ctx.globalAlpha=effectiveQuality==='low'?.18:effectiveQuality==='medium'?.24:.30;
 ctx.translate(ox-img.width,oy-img.height);
 ctx.fillStyle=groundPatternCache;
 ctx.fillRect(0,0,W+img.width*2,H+img.height*2);
 ctx.restore();
}
function drawVignette(){const g=ctx.createRadialGradient(W/2,H/2,H*.25,W/2,H/2,H*.75);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.55)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawBossHealthBar(){const b=enemies.find(e=>e.isBoss);if(!b)return;const bw=W*.5,bh=14,bx=W/2-bw/2,by=16;ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(bx-2,by-2,bw+4,bh+4);ctx.fillStyle='#3a0a15';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle='#d4af37';ctx.fillRect(bx,by,bw*clamp(b.hp/b.maxHp,0,1),bh);ctx.fillStyle='#f0e0d0';ctx.font='12px Georgia';ctx.textAlign='center';ctx.fillText(b.name,W/2,by+bh+14);}
function drawSouls(){for(const s of souls){const bob=Math.sin(gameTime*6+(s.x+s.y)*.01)*2.2;const [x,y]=worldToScreen(s.x,s.y+bob);ctx.save();ctx.globalAlpha=.26;ctx.fillStyle='#6e44c8';ctx.beginPath();ctx.ellipse(x,y+s.r+5,9,4,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.shadowColor='#9b72ff';ctx.shadowBlur=14;SpriteManager.drawPickup('soul',x,y,26,'●');ctx.restore();}for(const f of eternalFragments){const bob=Math.sin(gameTime*4+(f.x-f.y)*.008)*1.8;const [x,y]=worldToScreen(f.x,f.y+bob);ctx.save();ctx.globalAlpha=.24;ctx.fillStyle='#b88a1e';ctx.beginPath();ctx.ellipse(x,y+f.r+6,9,4,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(x,y);ctx.rotate(gameTime*1.2+((f.x+f.y)%15)*.08);ctx.shadowColor='#ffe070';ctx.shadowBlur=14;SpriteManager.drawPickup('fragment',0,0,28,'◆');ctx.restore();}for(const c of chests){if(c.opened)continue;const bob=Math.sin(gameTime*2+(c.x+c.y)*.002)*1.6;const [x,y]=worldToScreen(c.x,c.y+bob);ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(x,y+c.r+10,17,7,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.shadowColor='rgba(212,175,55,.35)';ctx.shadowBlur=10;SpriteManager.drawPickup('chest',x,y,54,'🧰');ctx.restore();}}
function drawParticles(){for(const p of particles){const [x,y]=worldToScreen(p.x,p.y);ctx.globalAlpha=clamp(p.life/24,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}}
function drawRingFx(x,y,r,color,alpha,spin){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,spin,spin+Math.PI*1.1);ctx.stroke();ctx.beginPath();ctx.arc(x,y,r*0.74,-spin*.9,-spin*.9+Math.PI*.85);ctx.stroke();ctx.restore();}
function drawSparkFx(x,y,color,count,phase,size){ctx.save();ctx.fillStyle=color;for(let i=0;i<count;i++){const a=phase+i*(Math.PI*2/count);const d=size*(.55+.45*Math.sin(phase*1.3+i));const px=x+Math.cos(a)*d,py=y+Math.sin(a)*d;ctx.globalAlpha=.18+.18*((i%3)+1);ctx.beginPath();ctx.arc(px,py,1.5+(i%2),0,Math.PI*2);ctx.fill();}ctx.restore();}
function drawBeamEyeFx(x,y,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=.55;ctx.strokeStyle='rgba(255,210,140,.85)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,11,6,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(180,30,50,.7)';ctx.beginPath();ctx.ellipse(0,0,2.5,5,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawAfterimageWeapon(type,x,y,size,rotation,alpha,frame){ctx.save();ctx.globalAlpha=alpha;SpriteManager.drawWeapon(type,x,y,size,rotation,'',frame);ctx.restore();}
function drawSlashes(){for(const s of slashes){const [x,y]=worldToScreen(s.x,s.y);const alpha=clamp(s.life/s.maxLife,0,1);ctx.save();ctx.strokeStyle=`rgba(184,28,69,${alpha})`;ctx.lineWidth=evolvedWeapons.chicote?8:6;ctx.beginPath();ctx.arc(x,y,s.range*.7,s.angle-Math.PI/2.5,s.angle+Math.PI/2.5);ctx.stroke();if(evolvedWeapons.chicote){ctx.strokeStyle=`rgba(255,120,150,${alpha*.7})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,s.range*.84,s.angle-Math.PI/2.1,s.angle+Math.PI/2.1);ctx.stroke();drawSparkFx(x,y,'rgba(255,70,110,.9)',6,s.angle+s.life*.1,s.range*.44);}const tipX=x+Math.cos(s.angle)*s.range*.52,tipY=y+Math.sin(s.angle)*s.range*.52;ctx.globalAlpha=.86*alpha;ctx.shadowColor='rgba(220,55,95,.45)';ctx.shadowBlur=10;SpriteManager.drawWeapon('chicote',tipX,tipY,evolvedWeapons.chicote?54:48,s.angle+.15,'🩸',getWeaponAnimFrameIndex('chicote',s.life*.12));ctx.restore();}}
function drawProjectiles(){for(const p of projectiles){const [x,y]=worldToScreen(p.x,p.y);if(p.type==='adaga'){const ang=Math.atan2(p.vy,p.vx)+Math.PI/2;const fr=getWeaponAnimFrameIndex('adaga',p.life*.05);ctx.save();ctx.shadowColor='#d93562';ctx.shadowBlur=12;if(evolvedWeapons.adaga){drawAfterimageWeapon('adaga',x-Math.cos(ang-Math.PI/2)*10,y-Math.sin(ang-Math.PI/2)*10,30,ang,.35,fr);drawAfterimageWeapon('adaga',x+Math.cos(ang-Math.PI/2)*10,y+Math.sin(ang-Math.PI/2)*10,30,ang,.35,fr);ctx.strokeStyle='rgba(255,80,120,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-p.vx*1.6,y-p.vy*1.6);ctx.lineTo(x,y);ctx.stroke();}SpriteManager.drawWeapon('adaga',x,y,evolvedWeapons.adaga?40:36,ang,'🗡️',fr);ctx.restore();continue;}if(p.type==='grimorio'){const fr=getWeaponAnimFrameIndex('grimorio',p.life*.04);ctx.save();ctx.globalAlpha=.96;ctx.shadowColor='rgba(140,40,80,.35)';ctx.shadowBlur=12;if(evolvedWeapons.grimorio){drawRingFx(x,y,24,'rgba(150,65,170,.55)',.8,gameTime*1.6);drawSparkFx(x,y,'rgba(235,160,255,.9)',4,gameTime*2+p.life*.03,18);}SpriteManager.drawWeapon('grimorio',x,y,evolvedWeapons.grimorio?44:40,gameTime*0.08+p.life*0.02,'📖',fr);ctx.restore();continue;}if(p.type==='cruz'){const fr=getWeaponAnimFrameIndex('cruz',p.life*.03);ctx.save();ctx.shadowColor='rgba(255,225,150,.42)';ctx.shadowBlur=12;if(evolvedWeapons.cruz){ctx.strokeStyle='rgba(255,230,160,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-16,y);ctx.lineTo(x+16,y);ctx.moveTo(x,y-16);ctx.lineTo(x,y+16);ctx.stroke();drawRingFx(x,y,20,'rgba(255,210,110,.42)',.7,-gameTime*1.2);}SpriteManager.drawWeapon('cruz',x,y,evolvedWeapons.cruz?46:42,gameTime*0.06+p.life*0.03,'✝️',fr);ctx.restore();continue;}ctx.fillStyle=p.type==='grimorio'?'#8a5ae0':p.type==='cruz'?'#d4af37':'#c9c9c9';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();}}
function drawOrbs(){for(const o of orbs){const [x,y]=worldToScreen(o.x,o.y);ctx.save();ctx.shadowColor='#8a5ae0';ctx.shadowBlur=16;ctx.globalAlpha=.94;if(evolvedWeapons.orbe){drawRingFx(x,y,26*player.areaMult,'rgba(120,80,220,.55)',.8,o.angle*1.2);drawSparkFx(x,y,'rgba(160,110,255,.9)',5,o.angle*2.1,20*player.areaMult);}SpriteManager.drawWeapon('orbe',x,y,(evolvedWeapons.orbe?42:34)*player.areaMult,o.angle*1.4,'🔮',getWeaponAnimFrameIndex('orbe',o.angle));ctx.restore();}}
function drawScythes(){for(const s of scythes){const [x,y]=worldToScreen(s.x,s.y);ctx.save();ctx.shadowColor='rgba(220,55,95,.45)';ctx.shadowBlur=16;if(evolvedWeapons.foice){ctx.strokeStyle='rgba(255,90,130,.42)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,18*player.areaMult,s.angle*2.5-.7,s.angle*2.5+.35);ctx.stroke();drawAfterimageWeapon('foice',x-Math.cos(s.angle*2.5)*10,y-Math.sin(s.angle*2.5)*10,36*player.areaMult,s.angle*2.5+.9,.28,getWeaponAnimFrameIndex('foice',s.angle+.5));}SpriteManager.drawWeapon('foice',x,y,(evolvedWeapons.foice?58:46)*player.areaMult,s.angle*2.5+.9,'🔱',getWeaponAnimFrameIndex('foice',s.angle));ctx.restore();}}
function drawLanterna(){const l=playerWeapons.lanterna;if(!l)return;const range=(evolvedWeapons.lanterna?220:160)*player.areaMult,half=evolvedWeapons.lanterna?Math.PI/3:(l>=5?Math.PI/4:Math.PI/6);ctx.save();ctx.translate(W/2,H/2);ctx.rotate(lastFacing);const g=ctx.createLinearGradient(0,0,range,0);g.addColorStop(0,'rgba(210,180,90,.3)');g.addColorStop(.2,evolvedWeapons.lanterna?'rgba(255,45,75,.3)':'rgba(235,90,70,.22)');g.addColorStop(1,'rgba(210,180,90,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,range,-half,half);ctx.closePath();ctx.fill();if(evolvedWeapons.lanterna){ctx.strokeStyle='rgba(255,210,120,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(20,0);ctx.lineTo(range*.72,0);ctx.stroke();}ctx.restore();if(evolvedWeapons.lanterna)drawBeamEyeFx(W/2+Math.cos(lastFacing)*90,H/2+Math.sin(lastFacing)*90,lastFacing);ctx.save();ctx.shadowColor='rgba(255,95,60,.38)';ctx.shadowBlur=14;SpriteManager.drawWeapon('lanterna',W/2+Math.cos(lastFacing)*18,H/2+Math.sin(lastFacing)*18,34,lastFacing+Math.PI/2,'🔦',getWeaponAnimFrameIndex('lanterna',stageTime*.05));ctx.restore();}
function drawEnemyProjectiles(){for(const p of enemyProjectiles){const [x,y]=worldToScreen(p.x,p.y);ctx.save();ctx.shadowColor='#ff315d';ctx.shadowBlur=18;ctx.fillStyle='#ff315d';ctx.beginPath();ctx.arc(x,y,Math.max(8,p.r),0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,210,220,.95)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,Math.max(5,p.r*.55),0,Math.PI*2);ctx.stroke();const speed=Math.hypot(p.vx||0,p.vy||0)||1;ctx.strokeStyle='rgba(255,49,93,.45)';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-(p.vx||0)/speed*20,y-(p.vy||0)/speed*20);ctx.stroke();ctx.restore();}}
function drawEnemies(){for(const e of enemies){const [x,y]=worldToScreen(e.x,e.y);if(x<-70||x>W+70||y<-70||y>H+70)continue;ctx.save();if(e.isElite){ctx.shadowColor='#d4af37';ctx.shadowBlur=20;}if(e.hitFlash>0)ctx.filter='brightness(2) saturate(0)';SpriteManager.drawEnemy(e,x,y,e.r*2.2,e.glyph);ctx.restore();if(e.hp<e.maxHp){const w=e.r*2;ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(x-w/2,y-e.r-10,w,4);ctx.fillStyle=e.isBoss?'#d4af37':e.isElite?'#e8c860':'#b81c45';ctx.fillRect(x-w/2,y-e.r-10,w*clamp(e.hp/e.maxHp,0,1),4);}}}
function drawDamageTexts(){for(const d of damageTexts){const [x,y]=worldToScreen(d.x,d.y);ctx.globalAlpha=clamp(d.life/(d.playerHit?34:26),0,1);ctx.fillStyle=d.color||'#ffe0a0';ctx.font=(d.playerHit?'bold 12px':'13px')+' Georgia';ctx.textAlign='center';if(d.playerHit){ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=5;}ctx.fillText(d.text,x,y);ctx.shadowBlur=0;ctx.globalAlpha=1;}}
function drawPlayer(){ctx.save();if(player.invuln>0&&Math.floor(player.invuln/4)%2===0)ctx.globalAlpha=.55;ctx.translate(W/2,H/2);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,20,18,9,0,0,Math.PI*2);ctx.fill();ctx.shadowColor='#7a1030';ctx.shadowBlur=12;SpriteManager.drawPlayer(0,0,84,'🧛‍♂️');ctx.restore();}
function drawBanner(){if(!banner)return;banner.life--;ctx.globalAlpha=clamp(banner.life/60,0,1);ctx.font='bold 26px Georgia';ctx.textAlign='center';ctx.fillStyle='#d4af37';ctx.fillText(banner.text,W/2,90);ctx.globalAlpha=1;if(banner.life<=0)banner=null;}
