"use strict";
function worldToScreen(x,y){return[x-player.x+W/2,y-player.y+H/2];}
function drawBackground(){const st=getStage(),img=AssetManager.get('bg:'+st.id);if(img){const scale=Math.max(W/img.width,H/img.height),iw=img.width*scale,ih=img.height*scale;ctx.drawImage(img,(W-iw)/2,(H-ih)/2,iw,ih);}else{ctx.fillStyle=['#0d0812','#100914','#090811','#13080d','#09070f','#060408'][currentStage]||'#0d0812';ctx.fillRect(0,0,W,H);const g=80,ox=((player.x%g)+g)%g,oy=((player.y%g)+g)%g;ctx.strokeStyle='rgba(110,60,100,.07)';for(let x=-ox;x<W;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=-oy;y<H;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}}drawFog();}
function drawVignette(){const g=ctx.createRadialGradient(W/2,H/2,H*.25,W/2,H/2,H*.75);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.55)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawBossHealthBar(){const b=enemies.find(e=>e.isBoss);if(!b)return;const bw=W*.5,bh=14,bx=W/2-bw/2,by=16;ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(bx-2,by-2,bw+4,bh+4);ctx.fillStyle='#3a0a15';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle='#d4af37';ctx.fillRect(bx,by,bw*clamp(b.hp/b.maxHp,0,1),bh);ctx.fillStyle='#f0e0d0';ctx.font='12px Georgia';ctx.textAlign='center';ctx.fillText(b.name,W/2,by+bh+14);}
function drawSouls(){for(const s of souls){const [x,y]=worldToScreen(s.x,s.y);ctx.fillStyle='#8a5ae0';ctx.shadowColor='#8a5ae0';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}for(const f of eternalFragments){const [x,y]=worldToScreen(f.x,f.y);ctx.fillStyle='#d4af37';ctx.shadowColor='#ffe070';ctx.shadowBlur=12;ctx.beginPath();for(let i=0;i<4;i++){const a=Math.PI/4+i*Math.PI/2,xx=x+Math.cos(a)*f.r,yy=y+Math.sin(a)*f.r;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.fill();ctx.shadowBlur=0;}for(const c of chests){if(c.opened)continue;const [x,y]=worldToScreen(c.x,c.y);ctx.font='28px serif';ctx.textAlign='center';ctx.fillText('🧰',x,y);}}
function drawParticles(){for(const p of particles){const [x,y]=worldToScreen(p.x,p.y);ctx.globalAlpha=clamp(p.life/24,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}}
function drawSlashes(){for(const s of slashes){const [x,y]=worldToScreen(s.x,s.y);ctx.strokeStyle=`rgba(184,28,69,${clamp(s.life/s.maxLife,0,1)})`;ctx.lineWidth=6;ctx.beginPath();ctx.arc(x,y,s.range*.7,s.angle-Math.PI/2.5,s.angle+Math.PI/2.5);ctx.stroke();}}
function drawProjectiles(){for(const p of projectiles){const [x,y]=worldToScreen(p.x,p.y);if(p.type==='adaga'){ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(p.vy,p.vx));ctx.shadowColor='#d93562';ctx.shadowBlur=12;ctx.fillStyle='#f14b78';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-7,-5);ctx.lineTo(-2,0);ctx.lineTo(-7,5);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,135,170,.9)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-10,0);ctx.lineTo(12,0);ctx.stroke();ctx.restore();continue;}ctx.fillStyle=p.type==='grimorio'?'#8a5ae0':p.type==='cruz'?'#d4af37':'#c9c9c9';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();}}
function drawOrbs(){for(const o of orbs){const [x,y]=worldToScreen(o.x,o.y);ctx.fillStyle=evolvedWeapons.orbe?'#170020':'#5a2a8a';ctx.shadowColor='#8a5ae0';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,(evolvedWeapons.orbe?14:10)*player.areaMult,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
function drawScythes(){for(const s of scythes){const [x,y]=worldToScreen(s.x,s.y);ctx.save();ctx.translate(x,y);ctx.rotate(s.angle*2.5);ctx.font=(evolvedWeapons.foice?22:16)*player.areaMult+'px serif';ctx.textAlign='center';ctx.fillText('🔱',0,0);ctx.restore();}}
function drawLanterna(){const l=playerWeapons.lanterna;if(!l)return;const range=(evolvedWeapons.lanterna?220:160)*player.areaMult,half=evolvedWeapons.lanterna?Math.PI/3:(l>=5?Math.PI/4:Math.PI/6);ctx.save();ctx.translate(W/2,H/2);ctx.rotate(lastFacing);const g=ctx.createLinearGradient(0,0,range,0);g.addColorStop(0,'rgba(210,180,90,.3)');g.addColorStop(1,'rgba(210,180,90,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,range,-half,half);ctx.closePath();ctx.fill();ctx.restore();}
function drawEnemyProjectiles(){for(const p of enemyProjectiles){const [x,y]=worldToScreen(p.x,p.y);ctx.fillStyle='#c0304a';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();}}
function drawEnemies(){for(const e of enemies){const [x,y]=worldToScreen(e.x,e.y);if(x<-70||x>W+70||y<-70||y>H+70)continue;ctx.save();if(e.isElite){ctx.shadowColor='#d4af37';ctx.shadowBlur=20;}if(e.hitFlash>0)ctx.filter='brightness(2) saturate(0)';SpriteManager.drawEnemy(e,x,y,e.r*2.2,e.glyph);ctx.restore();if(e.hp<e.maxHp){const w=e.r*2;ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(x-w/2,y-e.r-10,w,4);ctx.fillStyle=e.isBoss?'#d4af37':e.isElite?'#e8c860':'#b81c45';ctx.fillRect(x-w/2,y-e.r-10,w*clamp(e.hp/e.maxHp,0,1),4);}}}
function drawDamageTexts(){for(const d of damageTexts){const [x,y]=worldToScreen(d.x,d.y);ctx.globalAlpha=clamp(d.life/26,0,1);ctx.fillStyle='#ffe0a0';ctx.font='13px Georgia';ctx.textAlign='center';ctx.fillText(d.text,x,y);ctx.globalAlpha=1;}}
function drawPlayer(){ctx.save();if(player.invuln>0&&Math.floor(player.invuln/4)%2===0)ctx.globalAlpha=.55;ctx.translate(W/2,H/2);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,20,18,9,0,0,Math.PI*2);ctx.fill();ctx.shadowColor='#7a1030';ctx.shadowBlur=12;SpriteManager.drawPlayer(0,0,84,'🧛‍♂️');ctx.restore();}
function drawBanner(){if(!banner)return;banner.life--;ctx.globalAlpha=clamp(banner.life/60,0,1);ctx.font='bold 26px Georgia';ctx.textAlign='center';ctx.fillStyle='#d4af37';ctx.fillText(banner.text,W/2,90);ctx.globalAlpha=1;if(banner.life<=0)banner=null;}
