"use strict";
function worldToScreen(x,y){return[x-player.x+W/2,y-player.y+H/2];}
function hash2(ix,iy){const n=(ix*374761393+iy*668265263)>>>0;return ((n^(n>>>13))*1274126177)>>>0;}
function drawBackground(){const st=getStage(),img=AssetManager.get('bg:'+st.id);if(img){const b=getStageBounds();const camLeft=player.x-W/2, camTop=player.y-H/2;const worldW=Math.max(1,(b.maxX-b.minX)), worldH=Math.max(1,(b.maxY-b.minY));const u=clamp((camLeft-b.minX)/Math.max(1,worldW-W),0,1), v=clamp((camTop-b.minY)/Math.max(1,worldH-H),0,1);if(img.width>=W&&img.height>=H){const sx=Math.round(u*Math.max(0,img.width-W));const sy=Math.round(v*Math.max(0,img.height-H));ctx.drawImage(img,sx,sy,W,H,0,0,W,H);}else{const scale=Math.max(W/img.width,H/img.height),iw=img.width*scale,ih=img.height*scale,dx=-u*Math.max(0,iw-W),dy=-v*Math.max(0,ih-H);ctx.drawImage(img,dx,dy,iw,ih);}ctx.fillStyle='rgba(0,0,0,.08)';ctx.fillRect(0,0,W,H);}else{ctx.fillStyle=['#0d0812','#100914','#090811','#13080d','#09070f','#060408'][currentStage]||'#0d0812';ctx.fillRect(0,0,W,H);const g=80,ox=((player.x%g)+g)%g,oy=((player.y%g)+g)%g;ctx.strokeStyle='rgba(110,60,100,.07)';for(let x=-ox;x<W;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=-oy;y<H;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}}drawFog();}
function drawGroundLayer(){const st=getStage();if(st.id!=='stage0'){const cell=96,startX=Math.floor((player.x-W/2)/cell)-1,endX=Math.floor((player.x+W/2)/cell)+1,startY=Math.floor((player.y-H/2)/cell)-1,endY=Math.floor((player.y+H/2)/cell)+1;ctx.save();ctx.globalAlpha=.14;for(let gy=startY;gy<=endY;gy++){for(let gx=startX;gx<=endX;gx++){const [sx,sy]=worldToScreen(gx*cell+cell/2,gy*cell+cell/2);const h=hash2(gx,gy)%4;ctx.fillStyle=h===0?'rgba(255,255,255,.03)':h===1?'rgba(0,0,0,.08)':h===2?'rgba(130,70,150,.03)':'rgba(110,30,40,.03)';ctx.fillRect(sx-cell/2,sy-cell/2,cell,cell);}}ctx.restore();return;}const tileSize=96,stageId='stage0',tileKeys=['stoneA','stoneB','dirt','moss'],decalKeys=['decalGrass','decalCrack','decalBlood'];const startX=Math.floor((player.x-W/2)/tileSize)-1,endX=Math.floor((player.x+W/2)/tileSize)+1,startY=Math.floor((player.y-H/2)/tileSize)-1,endY=Math.floor((player.y+H/2)/tileSize)+1;const prev=ctx.imageSmoothingEnabled;ctx.imageSmoothingEnabled=false;for(let gy=startY;gy<=endY;gy++){for(let gx=startX;gx<=endX;gx++){const seed=hash2(gx,gy),[sx,sy]=worldToScreen(gx*tileSize+tileSize/2,gy*tileSize+tileSize/2),key=tileKeys[seed%tileKeys.length],img=getGroundAsset(stageId,key);if(img)ctx.drawImage(img,sx-tileSize/2,sy-tileSize/2,tileSize,tileSize);else{ctx.fillStyle='#453d45';ctx.fillRect(sx-tileSize/2,sy-tileSize/2,tileSize,tileSize);}if((seed>>>3)%5===0){const dkey=decalKeys[(seed>>>5)%decalKeys.length],decal=getGroundAsset(stageId,dkey);if(decal){ctx.globalAlpha=dkey==='decalBlood'?.38:.5;ctx.drawImage(decal,sx-tileSize/2,sy-tileSize/2,tileSize,tileSize);ctx.globalAlpha=1;}}}}ctx.imageSmoothingEnabled=prev;}
function drawVignette(){const g=ctx.createRadialGradient(W/2,H/2,H*.25,W/2,H/2,H*.75);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.55)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawBossHealthBar(){const b=enemies.find(e=>e.isBoss);if(!b)return;const bw=W*.5,bh=14,bx=W/2-bw/2,by=16;ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(bx-2,by-2,bw+4,bh+4);ctx.fillStyle='#3a0a15';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle='#d4af37';ctx.fillRect(bx,by,bw*clamp(b.hp/b.maxHp,0,1),bh);ctx.fillStyle='#f0e0d0';ctx.font='12px Georgia';ctx.textAlign='center';ctx.fillText(b.name,W/2,by+bh+14);}
function drawSouls(){for(const s of souls){const bob=Math.sin(gameTime*6+(s.x+s.y)*.01)*2.2;const [x,y]=worldToScreen(s.x,s.y+bob);ctx.save();ctx.globalAlpha=.26;ctx.fillStyle='#6e44c8';ctx.beginPath();ctx.ellipse(x,y+s.r+5,9,4,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.shadowColor='#9b72ff';ctx.shadowBlur=14;SpriteManager.drawPickup('soul',x,y,26,'●');ctx.restore();}for(const f of eternalFragments){const bob=Math.sin(gameTime*4+(f.x-f.y)*.008)*1.8;const [x,y]=worldToScreen(f.x,f.y+bob);ctx.save();ctx.globalAlpha=.24;ctx.fillStyle='#b88a1e';ctx.beginPath();ctx.ellipse(x,y+f.r+6,9,4,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(x,y);ctx.rotate(gameTime*1.2+((f.x+f.y)%15)*.08);ctx.shadowColor='#ffe070';ctx.shadowBlur=14;SpriteManager.drawPickup('fragment',0,0,28,'◆');ctx.restore();}for(const c of chests){if(c.opened)continue;const bob=Math.sin(gameTime*2+(c.x+c.y)*.002)*1.6;const [x,y]=worldToScreen(c.x,c.y+bob);ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(x,y+c.r+10,17,7,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.shadowColor='rgba(212,175,55,.35)';ctx.shadowBlur=10;SpriteManager.drawPickup('chest',x,y,54,'🧰');ctx.restore();}}
function drawParticles(){for(const p of particles){const [x,y]=worldToScreen(p.x,p.y);ctx.globalAlpha=clamp(p.life/24,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}}
function drawSlashes(){for(const s of slashes){const [x,y]=worldToScreen(s.x,s.y);ctx.strokeStyle=`rgba(184,28,69,${clamp(s.life/s.maxLife,0,1)})`;ctx.lineWidth=6;ctx.beginPath();ctx.arc(x,y,s.range*.7,s.angle-Math.PI/2.5,s.angle+Math.PI/2.5);ctx.stroke();}}
function drawProjectiles(){for(const p of projectiles){const [x,y]=worldToScreen(p.x,p.y);if(p.type==='adaga'){ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(p.vy,p.vx));ctx.shadowColor='#d93562';ctx.shadowBlur=12;ctx.fillStyle='#f14b78';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-7,-5);ctx.lineTo(-2,0);ctx.lineTo(-7,5);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,135,170,.9)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-10,0);ctx.lineTo(12,0);ctx.stroke();ctx.restore();continue;}ctx.fillStyle=p.type==='grimorio'?'#8a5ae0':p.type==='cruz'?'#d4af37':'#c9c9c9';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();}}
function drawOrbs(){for(const o of orbs){const [x,y]=worldToScreen(o.x,o.y);ctx.fillStyle=evolvedWeapons.orbe?'#170020':'#5a2a8a';ctx.shadowColor='#8a5ae0';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,(evolvedWeapons.orbe?14:10)*player.areaMult,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
function drawScythes(){for(const s of scythes){const [x,y]=worldToScreen(s.x,s.y);ctx.save();ctx.translate(x,y);ctx.rotate(s.angle*2.5);ctx.font=(evolvedWeapons.foice?22:16)*player.areaMult+'px serif';ctx.textAlign='center';ctx.fillText('🔱',0,0);ctx.restore();}}
function drawLanterna(){const l=playerWeapons.lanterna;if(!l)return;const range=(evolvedWeapons.lanterna?220:160)*player.areaMult,half=evolvedWeapons.lanterna?Math.PI/3:(l>=5?Math.PI/4:Math.PI/6);ctx.save();ctx.translate(W/2,H/2);ctx.rotate(lastFacing);const g=ctx.createLinearGradient(0,0,range,0);g.addColorStop(0,'rgba(210,180,90,.3)');g.addColorStop(1,'rgba(210,180,90,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,range,-half,half);ctx.closePath();ctx.fill();ctx.restore();}
function drawEnemyProjectiles(){for(const p of enemyProjectiles){const [x,y]=worldToScreen(p.x,p.y);ctx.fillStyle='#c0304a';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();}}
function drawEnemies(){for(const e of enemies){const [x,y]=worldToScreen(e.x,e.y);if(x<-70||x>W+70||y<-70||y>H+70)continue;ctx.save();if(e.isElite){ctx.shadowColor='#d4af37';ctx.shadowBlur=20;}if(e.hitFlash>0)ctx.filter='brightness(2) saturate(0)';SpriteManager.drawEnemy(e,x,y,e.r*2.2,e.glyph);ctx.restore();if(e.hp<e.maxHp){const w=e.r*2;ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(x-w/2,y-e.r-10,w,4);ctx.fillStyle=e.isBoss?'#d4af37':e.isElite?'#e8c860':'#b81c45';ctx.fillRect(x-w/2,y-e.r-10,w*clamp(e.hp/e.maxHp,0,1),4);}}}
function drawDamageTexts(){for(const d of damageTexts){const [x,y]=worldToScreen(d.x,d.y);ctx.globalAlpha=clamp(d.life/26,0,1);ctx.fillStyle='#ffe0a0';ctx.font='13px Georgia';ctx.textAlign='center';ctx.fillText(d.text,x,y);ctx.globalAlpha=1;}}
function drawPlayer(){ctx.save();if(player.invuln>0&&Math.floor(player.invuln/4)%2===0)ctx.globalAlpha=.55;ctx.translate(W/2,H/2);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,20,18,9,0,0,Math.PI*2);ctx.fill();ctx.shadowColor='#7a1030';ctx.shadowBlur=12;SpriteManager.drawPlayer(0,0,84,'🧛‍♂️');ctx.restore();}
function drawBanner(){if(!banner)return;banner.life--;ctx.globalAlpha=clamp(banner.life/60,0,1);ctx.font='bold 26px Georgia';ctx.textAlign='center';ctx.fillStyle='#d4af37';ctx.fillText(banner.text,W/2,90);ctx.globalAlpha=1;if(banner.life<=0)banner=null;}
