"use strict";
function resetGame(){
  player.x=0;player.y=0;player.hp=100;player.maxHp=100;player.level=1;player.xp=0;player.xpToNext=8;player.speed=2.6;player.dmgMult=1;player.areaMult=1;player.cooldownMult=1;player.magnetR=70;player.regen=0;player.invuln=0;player.lifesteal=0;player.blockChance=0;player.soulBonus=0;player.damageReduction=0;
  playerWeapons={adaga:1};playerPassives={};evolvedWeapons={};weaponTimers={adaga:0,chicote:0,orbe:0,grimorio:0,cruz:0,foice:0,lanterna:0};lanternaHitMap=new Map();
  releaseArrayToPool(projectiles,Pools.projectile);releaseArrayToPool(enemyProjectiles,Pools.enemyProjectile);releaseArrayToPool(souls,Pools.soul);releaseArrayToPool(eternalFragments,Pools.fragment);releaseArrayToPool(particles,Pools.particle);releaseArrayToPool(damageTexts,Pools.damageText);releaseArrayToPool(enemies,Pools.enemy);slashes.length=0;orbs.length=0;scythes.length=0;chests.length=0;
  gameTime=0;stageTime=0;killCount=0;eliteKills=0;bossKills=0;spawnTimer=0;runFragments=0;currentStage=0;stageBossSpawned=false;stageBossDefeated=false;stageCompleting=false;runStats={damageDealt:0,damageTaken:0,soulsCollected:0,fragmentsCollected:0,chestsOpened:0,highestLevel:1};
  running=true;paused=false;manualPause=false;pauseScreen.classList.remove('active');applyMetaUpgrades(true);rebuildOrbs();rebuildScythes();generateObstacles();resetPlayerAnimation();setPlayerMovementIntent(0,0,false);updateWeaponBar();updateHud();clearRunSave();
}
function applyMetaUpgrades(resetHp){const u=meta.upgrades||{};player.dmgMult*=1+(u.dano||0)*.04;player.maxHp+=(u.vida||0)*8;if(resetHp!==false)player.hp=player.maxHp;player.speed*=1+(u.velocidade||0)*.03;player.cooldownMult*=1-(u.recarga||0)*.02;player.magnetR+=(u.ima||0)*15;player.damageReduction=Math.min(.5,(u.armadura||0)*.02);xpGainMult=1+(u.xp||0)*.05;}
function rebuildOrbs(){const lvl=playerWeapons.orbe||0;const count=lvl>=4?2:1;orbs=[];if(lvl>0)for(let i=0;i<count;i++)orbs.push({angle:Math.PI*2/count*i,dist:evolvedWeapons.orbe?72:55});}
function rebuildScythes(){const lvl=playerWeapons.foice||0;const count=evolvedWeapons.foice?3:(lvl>=5?2:1);scythes=[];if(lvl>0)for(let i=0;i<count;i++)scythes.push({angle:Math.PI*2/count*i,dist:evolvedWeapons.foice?105:85,hitMap:new Map()});}
function makeEnemy(typeKey,x,y,opts){opts=opts||{};const def=ENEMY_TYPES[typeKey];if(!def)return null;const isElite=!!opts.isElite,scale=opts.scale??1,eliteMult=isElite?1.9:1;const e=Pools.enemy.acquire({id:enemyId++,type:typeKey,x,y,r:def.r*(isElite?1.3:1),hp:def.hp*scale*eliteMult,maxHp:def.hp*scale*eliteMult,speed:def.speed*(isElite?1.1:1),dmg:def.dmg*(isElite?1.4:1),color:def.color,xp:def.xp*(isElite?3:1),glyph:def.glyph,hitFlash:0,isBoss:false,isElite});if(typeKey==='gargula'){e.dashTimer=rand(80,140);e.dashing=false;e.dashTimeLeft=0;e.dashAngle=0;}if(typeKey==='necromante')e.summonTimer=rand(140,200);enemies.push(e);return e;}
function spawnEnemy(){const st=getStage();const typeKey=choice(st.enemyPool);const a=rand(0,Math.PI*2),d=Math.max(W,H)*.65;const scale=1+currentStage*.22+stageTime/300;const eliteChance=st.eliteChance+(meta.upgrades.sorte||0)*.002;makeEnemy(typeKey,player.x+Math.cos(a)*d,player.y+Math.sin(a)*d,{scale,isElite:Math.random()<eliteChance});}
function spawnBoss(key){if(enemies.some(e=>e.isBoss))return;const d=BOSS_TYPES[key];if(!d)return;const a=rand(0,Math.PI*2),sd=Math.max(W,H)*.55;const scale=1+currentStage*.12;const e=Pools.enemy.acquire({id:enemyId++,type:key,x:player.x+Math.cos(a)*sd,y:player.y+Math.sin(a)*sd,r:d.r,hp:d.hp*scale,maxHp:d.hp*scale,speed:d.speed,dmg:d.dmg,color:d.color,xp:d.xp,glyph:d.glyph,hitFlash:0,isBoss:true,isElite:false,name:d.name,atkTimer:80,atkInterval:d.atkInterval,atkSpread:d.atkSpread,summon:!!d.summon,summonTimer:d.summon?220:undefined});enemies.push(e);stageBossSpawned=true;spawnBanner(d.name+' desperta!');sfxBossSpawn();triggerShake(9,26);}
let banner=null;function spawnBanner(text){banner={text,life:180};}
function gainXp(amount){player.xp+=amount*xpGainMult;runStats.soulsCollected+=amount;while(player.xp>=player.xpToNext){player.xp-=player.xpToNext;player.level++;runStats.highestLevel=Math.max(runStats.highestLevel,player.level);player.xpToNext=Math.floor(8+player.level*5.5);triggerLevelUp();}}
function triggerLevelUp(){paused=true;sfxLevelUp();const options=buildUpgradeChoices();showChoiceOverlay('EVOLUÇÃO','Escolha uma bênção sombria',options);}
function showChoiceOverlay(title,sub,options){overlayTitle.textContent=title;overlaySub.textContent=sub;cardWrap.innerHTML='';options.forEach(opt=>{const card=document.createElement('div');card.className='card'+(opt.rarity?' rarity-'+opt.rarity:'');card.innerHTML=`${opt.tag?'<div class="newtag">'+opt.tag+'</div><br>':''}<div class="icon">${opt.icon}</div><div class="name">${opt.name}</div><div class="desc">${opt.desc}</div>`;card.onclick=()=>{opt.apply();overlay.classList.remove('active');paused=false;updateWeaponBar();};cardWrap.appendChild(card);});overlay.classList.add('active');}
function buildUpgradeChoices(){const pool=[];Object.keys(WEAPON_DEFS).filter(k=>!(k in playerWeapons)).forEach(k=>pool.push({kind:'newWeapon',key:k}));Object.keys(playerWeapons).filter(k=>playerWeapons[k]<WEAPON_DEFS[k].maxLevel).forEach(k=>pool.push({kind:'upgWeapon',key:k}));Object.keys(PASSIVE_DEFS).filter(k=>!(k in playerPassives)).forEach(k=>pool.push({kind:'newPassive',key:k}));Object.keys(playerPassives).filter(k=>playerPassives[k]<PASSIVE_DEFS[k].maxLevel).forEach(k=>pool.push({kind:'upgPassive',key:k}));for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}const picked=pool.slice(0,3);while(picked.length<3)picked.push({kind:'heal'});return picked.map(p=>{if(p.kind==='newWeapon'){const d=WEAPON_DEFS[p.key];return{icon:d.icon,name:d.name,desc:d.desc(1),tag:'NOVO',rarity:'uncommon',apply:()=>{playerWeapons[p.key]=1;if(p.key==='orbe')rebuildOrbs();if(p.key==='foice')rebuildScythes();}};}if(p.kind==='upgWeapon'){const d=WEAPON_DEFS[p.key],n=playerWeapons[p.key]+1;return{icon:d.icon,name:d.name+' Nv.'+n,desc:d.desc(n),rarity:n>=7?'rare':'common',apply:()=>{playerWeapons[p.key]=n;if(p.key==='orbe')rebuildOrbs();if(p.key==='foice')rebuildScythes();}};}if(p.kind==='newPassive'){const d=PASSIVE_DEFS[p.key];return{icon:d.icon,name:d.name,desc:d.desc,tag:'NOVO',rarity:'uncommon',apply:()=>{playerPassives[p.key]=1;applyPassiveEffect(p.key);}};}if(p.kind==='upgPassive'){const d=PASSIVE_DEFS[p.key],n=playerPassives[p.key]+1;return{icon:d.icon,name:d.name+' Nv.'+n,desc:d.desc,rarity:'common',apply:()=>{playerPassives[p.key]=n;applyPassiveEffect(p.key);}};}return{icon:'🌙',name:'Bênção Lunar',desc:'Restaura 40% da vida máxima.',rarity:'common',apply:()=>player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.4)};});}
function applyPassiveEffect(k){if(k==='vigor'){player.maxHp+=20;player.hp+=20;}if(k==='velocidade')player.speed*=1.1;if(k==='forca')player.dmgMult*=1.15;if(k==='area')player.areaMult*=1.15;if(k==='cadencia')player.cooldownMult*=.9;if(k==='ima')player.magnetR+=40;if(k==='regen')player.regen+=1;if(k==='vampirismo')player.lifesteal+=.02;if(k==='escudo')player.blockChance+=.15;if(k==='sorte')player.soulBonus+=.1;}
function eligibleEvolutions(){return Object.keys(playerWeapons).filter(k=>!evolvedWeapons[k]&&playerWeapons[k]>=WEAPON_DEFS[k].maxLevel&&playerPassives[EVOLUTION_DEFS[k]?.requiresPassive]>0);}
function evolveWeapon(k){evolvedWeapons[k]=true;if(k==='orbe')rebuildOrbs();if(k==='foice')rebuildScythes();spawnBanner((EVOLUTION_DEFS[k]?.name||'Arma evoluída')+' despertou!');}
