"use strict";
function updatePlayer(dt){
  let dx=0,dy=0;
  if(actionPressed('up'))dy-=1;
  if(actionPressed('down'))dy+=1;
  if(actionPressed('left'))dx-=1;
  if(actionPressed('right'))dx+=1;
  const gp=readGamepad();
  if(gp.active){dx=gp.x;dy=gp.y;}
  let moving=false;
  if(dx||dy){
    const l=Math.hypot(dx,dy)||1;
    dx/=l;dy/=l;
    player.x+=dx*player.speed*dt;
    player.y+=dy*player.speed*dt;
    lastFacing=Math.atan2(dy,dx);
    moving=true;
  }
  setPlayerMovementIntent(dx,dy,moving);
  clampPlayerToStage();
  if(player.invuln>0)player.invuln-=dt;
  if(player.regen>0)player.hp=Math.min(player.maxHp,player.hp+player.regen*dt/60);
}
function updateOrbs(dt){const l=playerWeapons.orbe;if(!l)return;const dmg=WEAPON_DEFS.orbe.baseDamage*player.dmgMult*(1+(l-1)*.18)*weaponDamageMult('orbe');for(const o of orbs){o.angle+=(evolvedWeapons.orbe?.08:.06)*dt;o.x=player.x+Math.cos(o.angle)*o.dist*player.areaMult;o.y=player.y+Math.sin(o.angle)*o.dist*player.areaMult;for(const e of nearbyEnemies(o.x,o.y,50)){const rr=10*player.areaMult+e.r;if(dist2(o.x,o.y,e.x,e.y)<rr*rr)damageEnemy(e,dmg*dt/8,true);}}}
function updateScythes(dt){const l=playerWeapons.foice;if(!l)return;const dmg=WEAPON_DEFS.foice.baseDamage*player.dmgMult*(1+(l-1)*.18)*weaponDamageMult('foice');for(const sc of scythes){sc.angle+=(evolvedWeapons.foice?.14:.1)*dt;sc.x=player.x+Math.cos(sc.angle)*sc.dist*player.areaMult;sc.y=player.y+Math.sin(sc.angle)*sc.dist*player.areaMult;for(const e of nearbyEnemies(sc.x,sc.y,60)){const rr=(evolvedWeapons.foice?16:12)*player.areaMult+e.r,cd=sc.hitMap.get(e.id)||0;if(cd<=0&&dist2(sc.x,sc.y,e.x,e.y)<rr*rr){damageEnemy(e,dmg);sc.hitMap.set(e.id,evolvedWeapons.foice?7:11);}}for(const [id,t] of sc.hitMap){const nt=t-dt;nt<=0?sc.hitMap.delete(id):sc.hitMap.set(id,nt);}}}
function updateLanterna(dt){const l=playerWeapons.lanterna;if(!l)return;const dmg=WEAPON_DEFS.lanterna.baseDamage*player.dmgMult*(1+(l-1)*.18)*weaponDamageMult('lanterna'),range=(evolvedWeapons.lanterna?220:160)*player.areaMult,half=evolvedWeapons.lanterna?Math.PI/3:(l>=5?Math.PI/4:Math.PI/6);for(const e of nearbyEnemies(player.x,player.y,range)){const dx=e.x-player.x,dy=e.y-player.y,d=Math.hypot(dx,dy);if(d>range)continue;const diff=Math.atan2(Math.sin(Math.atan2(dy,dx)-lastFacing),Math.cos(Math.atan2(dy,dx)-lastFacing));if(Math.abs(diff)<=half&&(lanternaHitMap.get(e.id)||0)<=0){damageEnemy(e,dmg);lanternaHitMap.set(e.id,evolvedWeapons.lanterna?8:14);}}for(const [id,t] of lanternaHitMap){const nt=t-dt;nt<=0?lanternaHitMap.delete(id):lanternaHitMap.set(id,nt);}}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.homing){const t=nearestEnemy(p.x,p.y,220);if(t){const ta=Math.atan2(t.y-p.y,t.x-p.x),cs=Math.hypot(p.vx,p.vy)||1,ca=Math.atan2(p.vy,p.vx),na=ca+Math.atan2(Math.sin(ta-ca),Math.cos(ta-ca))*.08*dt;p.vx=Math.cos(na)*cs;p.vy=Math.sin(na)*cs;}}if(p.life<=0){Pools.projectile.release(projectiles.splice(i,1)[0]);continue;}for(const e of nearbyEnemies(p.x,p.y,70)){const rr=p.r+e.r;if(dist2(p.x,p.y,e.x,e.y)<rr*rr&&!p.hitSet.has(e.id)){p.hitSet.add(e.id);damageEnemy(e,p.dmg);p.pierce--;if(p.type==='adaga')spawnParticles(e.x,e.y,'#b81c45',8);if(p.pierce<=0){Pools.projectile.release(projectiles.splice(i,1)[0]);break;}}}}}
function updateSlashes(dt){for(let i=slashes.length-1;i>=0;i--){const s=slashes[i];s.life-=dt;const angRange=Math.PI/2.3;for(const e of nearbyEnemies(s.x,s.y,s.range+40)){if(s.hitSet.has(e.id))continue;const dx=e.x-s.x,dy=e.y-s.y,d=Math.hypot(dx,dy);if(d>s.range+e.r)continue;let diff=Math.atan2(Math.sin(Math.atan2(dy,dx)-s.angle),Math.cos(Math.atan2(dy,dx)-s.angle));if(Math.abs(diff)<=angRange/2){s.hitSet.add(e.id);damageEnemy(e,s.dmg);spawnParticles(e.x,e.y,'#b81c45',10);}}if(s.life<=0)slashes.splice(i,1);}}
function updateEnemies(dt){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];const a=Math.atan2(player.y-e.y,player.x-e.x);if(e.type==='gargula'){if(e.dashing){e.dashTimeLeft-=dt;e.x+=Math.cos(e.dashAngle)*e.speed*5*dt;e.y+=Math.sin(e.dashAngle)*e.speed*5*dt;if(e.dashTimeLeft<=0)e.dashing=false;}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;e.dashTimer-=dt;if(e.dashTimer<=0){e.dashing=true;e.dashTimeLeft=18;e.dashAngle=a;e.dashTimer=rand(100,160);}}}else if(e.type==='necromante'){if(Math.hypot(player.x-e.x,player.y-e.y)>220){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}e.summonTimer-=dt;if(e.summonTimer<=0){e.summonTimer=rand(160,220);for(let s=0;s<2;s++){const aa=rand(0,Math.PI*2);makeEnemy('morcego',e.x+Math.cos(aa)*30,e.y+Math.sin(aa)*30,{});}sfxSummon();}}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}if(e.hitFlash>0)e.hitFlash-=dt;if(e.isBoss){e.atkTimer-=dt;if(e.atkTimer<=0){e.atkTimer=e.atkInterval;const base=Math.atan2(player.y-e.y,player.x-e.x),spread=e.atkSpread||1;for(let k=0;k<spread;k++){const aa=base+(k-(spread-1)/2)*.35;enemyProjectiles.push(Pools.enemyProjectile.acquire({x:e.x,y:e.y,vx:Math.cos(aa)*3.4,vy:Math.sin(aa)*3.4,r:9,dmg:e.dmg*.6,life:150}));}}if(e.summon){e.summonTimer-=dt;if(e.summonTimer<=0){e.summonTimer=260;for(let s=0;s<3;s++){const aa=rand(0,Math.PI*2);makeEnemy('esqueleto',e.x+Math.cos(aa)*50,e.y+Math.sin(aa)*50,{});}sfxSummon();}}}const rr=e.r+player.r;if(dist2(e.x,e.y,player.x,player.y)<rr*rr&&player.invuln<=0){if(player.blockChance&&Math.random()<player.blockChance){sfxBlock();player.invuln=20;}else{const taken=e.dmg*(1-player.damageReduction);player.hp-=taken;runStats.damageTaken+=taken;player.invuln=35;sfxPlayerHurt();triggerPlayerHurt();triggerShake(5,12);if(player.hp<=0){beginGameOverSequence();return;}}}}}
function updateEnemyProjectiles(dt){for(let i=enemyProjectiles.length-1;i>=0;i--){const p=enemyProjectiles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0){Pools.enemyProjectile.release(enemyProjectiles.splice(i,1)[0]);continue;}const rr=p.r+player.r;if(dist2(p.x,p.y,player.x,player.y)<rr*rr){Pools.enemyProjectile.release(enemyProjectiles.splice(i,1)[0]);if(player.invuln<=0){const taken=p.dmg*(1-player.damageReduction);player.hp-=taken;runStats.damageTaken+=taken;player.invuln=30;sfxPlayerHurt();triggerPlayerHurt();if(player.hp<=0){beginGameOverSequence();return;}}}}}
function damageEnemy(e,dmg,dot){e.hp-=dmg;e.hitFlash=4;if(!dot&&gameplaySettings.damageNumbers)damageTexts.push(Pools.damageText.acquire({x:e.x,y:e.y,vy:-.35,life:26,text:Math.round(dmg)}));runStats.damageDealt+=dmg;if(player.lifesteal)player.hp=Math.min(player.maxHp,player.hp+dmg*player.lifesteal*.02);if(e.hp<=0)killEnemy(e);}
function killEnemy(e){const idx=enemies.indexOf(e);if(idx>=0)enemies.splice(idx,1);spawnParticles(e.x,e.y,e.isBoss?'#d4af37':e.isElite?'#e8c860':e.color, e.isBoss?28:e.isElite?16:8);for(let i=0;i<(e.isBoss?6:e.isElite?3:1);i++)souls.push(Pools.soul.acquire({x:e.x+rand(-10,10),y:e.y+rand(-10,10),r:6,val:1+(e.isBoss?4:0)+(e.isElite?1:0)}));killCount++;if(e.isElite)eliteKills++;if(e.isBoss){bossKills++;stageBossDefeated=true;for(let i=0;i<8;i++)spawnFragment(e.x+rand(-25,25),e.y+rand(-25,25),1);spawnChest(e.x,e.y);}else if(e.isElite&&Math.random()<.55+(meta.upgrades.sorte||0)*.02){spawnFragment(e.x,e.y,1);}Pools.enemy.release(e);}
function spawnFragment(x,y,val){eternalFragments.push(Pools.fragment.acquire({x,y,val:val||1,r:7}));}
function spawnChest(x,y){chests.push({x,y,r:15,opened:false});spawnBanner('Um baú amaldiçoado surgiu!');}
function openChest(c){if(c.opened)return;c.opened=true;runStats.chestsOpened++;const evo=eligibleEvolutions();const opts=[];if(evo.length){const k=choice(evo),d=EVOLUTION_DEFS[k];opts.push({icon:d.icon,name:d.name,desc:'Evolução definitiva de '+WEAPON_DEFS[k].name+'.',tag:'EVOLUÇÃO',rarity:'cursed',apply:()=>evolveWeapon(k)});}opts.push({icon:'💠',name:'Fragmentos Eternos',desc:'+5 moedas permanentes.',rarity:'rare',apply:()=>addPermanentCurrency(5)});opts.push({icon:'❤️',name:'Sangue Restaurado',desc:'Cura 60% e aumenta a vida máxima em 10.',rarity:'uncommon',apply:()=>{player.maxHp+=10;player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.6);}});paused=true;showChoiceOverlay('BAÚ AMALDIÇOADO','Escolha sua recompensa',opts.slice(0,3));}
function spawnParticles(x,y,color,n){const limit=effectiveQuality==='low'?Math.ceil(n*.3):effectiveQuality==='medium'?Math.ceil(n*.6):n;for(let i=0;i<limit;i++){const a=rand(0,Math.PI*2),sp=rand(1,3.5);particles.push(Pools.particle.acquire({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:24,color,r:rand(1.5,3.5)}));}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.92;p.vy*=.92;p.life-=dt;if(p.life<=0)Pools.particle.release(particles.splice(i,1)[0]);}for(let i=damageTexts.length-1;i>=0;i--){const d=damageTexts[i];d.y+=d.vy*dt;d.life-=dt;if(d.life<=0)Pools.damageText.release(damageTexts.splice(i,1)[0]);}}
function updatePickups(dt){for(let i=souls.length-1;i>=0;i--){const s=souls[i],d=Math.hypot(s.x-player.x,s.y-player.y);if(d<player.magnetR){const a=Math.atan2(player.y-s.y,player.x-s.x),pull=clamp((player.magnetR-d)/player.magnetR,.2,1)*6;s.x+=Math.cos(a)*pull*dt;s.y+=Math.sin(a)*pull*dt;}if(d<player.r+s.r+6){gainXp(s.val);Pools.soul.release(souls.splice(i,1)[0]);sfxPickup();}}
 for(let i=eternalFragments.length-1;i>=0;i--){const f=eternalFragments[i],d=Math.hypot(f.x-player.x,f.y-player.y);if(d<player.magnetR*1.1){const a=Math.atan2(player.y-f.y,player.x-f.x);f.x+=Math.cos(a)*7*dt;f.y+=Math.sin(a)*7*dt;}if(d<player.r+f.r+8){addPermanentCurrency(f.val);Pools.fragment.release(eternalFragments.splice(i,1)[0]);sfxPickup();}}
 for(const c of chests)if(!c.opened&&dist2(c.x,c.y,player.x,player.y)<(c.r+player.r+8)**2)openChest(c);
}
